#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="POS_System")]
	public partial class Employee_dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEmployee_Detail(Employee_Detail instance);
    partial void UpdateEmployee_Detail(Employee_Detail instance);
    partial void DeleteEmployee_Detail(Employee_Detail instance);
    #endregion
		
		public Employee_dbDataContext() : 
				base(global::DataLayer.Properties.Settings.Default.POS_SystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Employee_dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Employee_dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Employee_dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Employee_dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Employee_Detail> Employee_Details
		{
			get
			{
				return this.GetTable<Employee_Detail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee_Details")]
	public partial class Employee_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Employee_ID;
		
		private string _Employee_Name;
		
		private string _Employee_Gender;
		
		private string _Employee_Age;
		
		private string _Employee_NID;
		
		private string _Employee_MaritalStatus;
		
		private string _Employee_JobPosition;
		
		private string _Employee_StartDate;
		
		private string _Employee_EndDate;
		
		private string _Employee_JobDuration;
		
		private string _Employee_Address;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmployee_IDChanging(string value);
    partial void OnEmployee_IDChanged();
    partial void OnEmployee_NameChanging(string value);
    partial void OnEmployee_NameChanged();
    partial void OnEmployee_GenderChanging(string value);
    partial void OnEmployee_GenderChanged();
    partial void OnEmployee_AgeChanging(string value);
    partial void OnEmployee_AgeChanged();
    partial void OnEmployee_NIDChanging(string value);
    partial void OnEmployee_NIDChanged();
    partial void OnEmployee_MaritalStatusChanging(string value);
    partial void OnEmployee_MaritalStatusChanged();
    partial void OnEmployee_JobPositionChanging(string value);
    partial void OnEmployee_JobPositionChanged();
    partial void OnEmployee_StartDateChanging(string value);
    partial void OnEmployee_StartDateChanged();
    partial void OnEmployee_EndDateChanging(string value);
    partial void OnEmployee_EndDateChanged();
    partial void OnEmployee_JobDurationChanging(string value);
    partial void OnEmployee_JobDurationChanged();
    partial void OnEmployee_AddressChanging(string value);
    partial void OnEmployee_AddressChanged();
    #endregion
		
		public Employee_Detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Employee_ID
		{
			get
			{
				return this._Employee_ID;
			}
			set
			{
				if ((this._Employee_ID != value))
				{
					this.OnEmployee_IDChanging(value);
					this.SendPropertyChanging();
					this._Employee_ID = value;
					this.SendPropertyChanged("Employee_ID");
					this.OnEmployee_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Employee_Name
		{
			get
			{
				return this._Employee_Name;
			}
			set
			{
				if ((this._Employee_Name != value))
				{
					this.OnEmployee_NameChanging(value);
					this.SendPropertyChanging();
					this._Employee_Name = value;
					this.SendPropertyChanged("Employee_Name");
					this.OnEmployee_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_Gender", DbType="NVarChar(50)")]
		public string Employee_Gender
		{
			get
			{
				return this._Employee_Gender;
			}
			set
			{
				if ((this._Employee_Gender != value))
				{
					this.OnEmployee_GenderChanging(value);
					this.SendPropertyChanging();
					this._Employee_Gender = value;
					this.SendPropertyChanged("Employee_Gender");
					this.OnEmployee_GenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_Age", DbType="NVarChar(50)")]
		public string Employee_Age
		{
			get
			{
				return this._Employee_Age;
			}
			set
			{
				if ((this._Employee_Age != value))
				{
					this.OnEmployee_AgeChanging(value);
					this.SendPropertyChanging();
					this._Employee_Age = value;
					this.SendPropertyChanged("Employee_Age");
					this.OnEmployee_AgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_NID", DbType="NVarChar(50)")]
		public string Employee_NID
		{
			get
			{
				return this._Employee_NID;
			}
			set
			{
				if ((this._Employee_NID != value))
				{
					this.OnEmployee_NIDChanging(value);
					this.SendPropertyChanging();
					this._Employee_NID = value;
					this.SendPropertyChanged("Employee_NID");
					this.OnEmployee_NIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_MaritalStatus", DbType="NVarChar(50)")]
		public string Employee_MaritalStatus
		{
			get
			{
				return this._Employee_MaritalStatus;
			}
			set
			{
				if ((this._Employee_MaritalStatus != value))
				{
					this.OnEmployee_MaritalStatusChanging(value);
					this.SendPropertyChanging();
					this._Employee_MaritalStatus = value;
					this.SendPropertyChanged("Employee_MaritalStatus");
					this.OnEmployee_MaritalStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_JobPosition", DbType="NVarChar(50)")]
		public string Employee_JobPosition
		{
			get
			{
				return this._Employee_JobPosition;
			}
			set
			{
				if ((this._Employee_JobPosition != value))
				{
					this.OnEmployee_JobPositionChanging(value);
					this.SendPropertyChanging();
					this._Employee_JobPosition = value;
					this.SendPropertyChanged("Employee_JobPosition");
					this.OnEmployee_JobPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_StartDate", DbType="NVarChar(50)")]
		public string Employee_StartDate
		{
			get
			{
				return this._Employee_StartDate;
			}
			set
			{
				if ((this._Employee_StartDate != value))
				{
					this.OnEmployee_StartDateChanging(value);
					this.SendPropertyChanging();
					this._Employee_StartDate = value;
					this.SendPropertyChanged("Employee_StartDate");
					this.OnEmployee_StartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_EndDate", DbType="NVarChar(50)")]
		public string Employee_EndDate
		{
			get
			{
				return this._Employee_EndDate;
			}
			set
			{
				if ((this._Employee_EndDate != value))
				{
					this.OnEmployee_EndDateChanging(value);
					this.SendPropertyChanging();
					this._Employee_EndDate = value;
					this.SendPropertyChanged("Employee_EndDate");
					this.OnEmployee_EndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_JobDuration", DbType="NVarChar(50)")]
		public string Employee_JobDuration
		{
			get
			{
				return this._Employee_JobDuration;
			}
			set
			{
				if ((this._Employee_JobDuration != value))
				{
					this.OnEmployee_JobDurationChanging(value);
					this.SendPropertyChanging();
					this._Employee_JobDuration = value;
					this.SendPropertyChanged("Employee_JobDuration");
					this.OnEmployee_JobDurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_Address", DbType="NVarChar(50)")]
		public string Employee_Address
		{
			get
			{
				return this._Employee_Address;
			}
			set
			{
				if ((this._Employee_Address != value))
				{
					this.OnEmployee_AddressChanging(value);
					this.SendPropertyChanging();
					this._Employee_Address = value;
					this.SendPropertyChanged("Employee_Address");
					this.OnEmployee_AddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
